### ISSUE TITLE
MINIO Minor issues

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/hexabot-helper-minio#1]
Here are the issues encountered and suggestions for improvement during the MinIO installation process:
- [ ] Port Configuration Issue: In the docker-compose.minio.dev.yml file, the MINIO_CONSOLE_PORT environment variable should be configured in the .env file with a value of 9001.
- [ ] Admin Panel Settings: The "Settings > MinIO" option does not appear in the admin panel after running the setup.
- [ ] MinIO Client Initialization Issue:
      The minio-mc container won't start unless the following environment variables are provided:
          MINIO_ROOT_USER
          MINIO_ROOT_PASSWORD
          MINIO_DEFAULT_BUCKET_NAME
and I had to add them all manually as their values are not mentioned in the documentation nor initialized automayically when installing the helper

Bucket Creation in MinIO: in the docker-compose.minio.yml ("minio/${MINIO_DEFAULT_BUCKET_NAME}") you can't create a bucket under minio unless you specify minio as an alias here is a the correct version of minio-mc container configuration:
```
  minio-mc:
  image: minio/mc
  container_name: minio-mc
  depends_on:
    minio:
      condition: service_healthy
      restart: true
  entrypoint: >/bin/sh -c "/usr/bin/mc alias set minio http://minio:9000/ ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} && /usr/bin/mc mb --quiet minio/${MINIO_DEFAULT_BUCKET_NAME}"
  networks:
minio-network
```
with this update, the minio client will be able to create a bucket successfully

I think it is better in the README file, in the Installation section, under the 5th step to link it to the Setting configuration section

I attached some screenshots to help you visualize the problems i had, and I can't go further with the testing since minio option doesn't appear in the admin panel
